@startuml Memotions Sequence Diagram

participant "Android" as AN
participant "Backend API" as BA
participant "ML API" as ML
queue "Pub/Sub" as PS
database "Database" as DB

== Journal Created with Published Status ==
AN -> BA: Submit Journal (status = published)
BA -> DB: Store Journal
DB --> BA: Journal Stored
BA -> PS: Publish "journals.published"

== Emotion Analysis ==
PS -> ML: Push "journals.published"
ML -> DB: Fetch Journal Data
ML -> ML: Predict Emotions
ML -> DB: Store Emotion Analysis
ML -> DB: Store Feedbacks
DB --> ML: Analysis and Feedback Stored
ML -> PS: Publish "feedback.generated"

== Update Journal Status ==
PS -> BA: Push "feedback.generated"
BA -> DB: Update Journal Status (status = analyzed)
DB --> BA: Status Updated

@enduml
