on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Name of the target environment.    
      ref:  
        type: string
        required: true
        description: The tag or SHA to checkout.

jobs:
  code-quality:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run ESLint
      - name: Run ESLint
        run: npm run lint

  build-and-release:
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.PROD_GOOGLE_CREDENTIALS }}'
          token_format: 'access_token'

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ vars.PROD_REGION }}-docker.pkg.dev'

      - name: Build, tag and push container
        id: build-image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true 
          tags: |
            ${{ vars.PROD_REGION }}-docker.pkg.dev/${{ vars.PROD_GCP_PROJECT_ID }}/${{ vars.BACKEND_ARTIFACT_REPO }}/${{ vars.BACKEND_SERVICE_NAME }}:${{ inputs.ref }}
    
  manual-approval:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: checkin
        run: echo ${{ github.token }}
      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.TOKEN }}
          approvers: "GungIndi,bayskie"
          minimum-approvals: 1
          timeout-minutes: 10
          issue-title: "Approve Production Deployment"
          issue-body: "Please review and approve deployment to production"

  deploy-to-production:
    needs: manual-approval
    runs-on: ubuntu-latest
    steps:
      
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.PROD_GOOGLE_CREDENTIALS }}'
          token_format: 'access_token'
      - name: Deploy to Cloud Runn
        id: deploy
        run: |
          gcloud run deploy ${{ vars.BACKEND_SERVICE_NAME }} \
          --image=${{ vars.PROD_REGION }}-docker.pkg.dev/${{ vars.PROD_GCP_PROJECT_ID }}/${{ vars.BACKEND_ARTIFACT_REPO }}/${{ vars.BACKEND_SERVICE_NAME }}:${{ inputs.ref }} \
          --region=${{ vars.PROD_REGION }} \
          --project=${{ vars.PROD_GCP_PROJECT_ID }} \
          --port=8000 \
          --cpu=2 \
          --memory=1Gi \
          --min-instances=1 \
          --max-instances=2 \
          --set-env-vars=ENVIRONMENT=production,DATABASE_URL=${{ secrets.DATABASE_URL }},JWT_SECRET=${{ secrets.JWT_SECRET}},TOPIC_ID=${{ vars.BACKEND_TOPIC_ID }} \
          && gcloud run services update-traffic ${{ vars.BACKEND_SERVICE_NAME }} --region=${{ vars.PROD_REGION }} --to-latest
